name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rust dependency cache
      uses: Swatinem/rust-cache@v2
    - name: Compile and run tests
      run: cargo test  # --verbose
